#!/usr/bin/python

import sys
import argparse
import configparser
import json
import re
from functools import reduce

parser = argparse.ArgumentParser(
    description="Compile config from INI human-readable format to binary")
parser.add_argument('-s', '--schema', required=True,
    help='File with the compilation schema for the config')
parser.add_argument('ini_file',
    help='Input file in INI format')
parser.add_argument('bin_file',
    help='Output file saved as a binary blob')
args = parser.parse_args()

class FieldValueError(Exception):
    pass

class Bitfield:
    def __init__(self, word, bit, width, vmap=None):
        self.word = word
        self.bit = bit
        self.width = width
        self.vmask = (1 << self.width) - 1
        self.vmap = vmap

    def map(self, v):
        try:
            if self.vmap is None:
                return v
            return self.vmap[v]
        except KeyError:
            raise FieldValueError("value '%s' not one of: {%s}" % \
                                  (v, ",".join(self.vmap.keys())))
    def build(self, val):
        v = reduce(lambda x, y: x | self.map(y), val.split(), 0x0)
        if v & self.vmask != v:
            raise FieldValueError("value 0x%x wider than field width %u" % (v, self.width))
        return (v & self.vmask) << self.bit

class ConfigError(Exception):
    pass
class ConfigKeyError(ConfigError):
    pass
class ConfigValueError(ConfigError):
    pass

def strip_comments(s):
    return re.sub(r'//.*', '', s)

BYTES_IN_WORD = 4
def bytearray_from_wordarray(wa):
    ba = []
    for w in wa:
        for i in range(0, BYTES_IN_WORD):
            ba += [(w & (0xff << (8 * i))) >> (8 * i)]
    return bytearray(ba)

def compile(cfg, schema):
    cfg_bin = [] # list of words
    for s in cfg.sections():
        if s not in schema:
            raise ConfigKeyError("section '%s' not in schema" % s)
        sect_sch = schema[s]
        for k in cfg[s]:
            if k not in sect_sch:
                raise ConfigKeyError("field '%s' not in schema for section '%s'" % \
                                     (k, s))
            try:
                v = cfg[s][k]
                f_spec = sect_sch[k]
                f = Bitfield(word=f_spec[0], bit=f_spec[1], width=f_spec[2], vmap=f_spec[3])
                if f.word >= len(cfg_bin):
                    cfg_bin.extend([0x0] * (f.word + 1 - len(cfg_bin)))
                cfg_bin[f.word] |= f.build(v)
            except FieldValueError as exc:
                raise ConfigValueError("field %s.%s value '%s' invalid: %s" % \
                                       (s, k, v, exc.args[0]))
    return bytearray_from_wordarray(cfg_bin)

try:
    schema = json.loads(strip_comments(open(args.schema, "r").read()))
except Exception as exc:
    print("Error in ", args.schema, ":", exc.args[0])
    sys.exit(1)

try:
    cfg = configparser.ConfigParser()
    cfg.read(args.ini_file)
except Exception as exc:
    print("Error in ", args.ini_file, ":", exc.args[0])
    sys.exit(1)

try:
    binary = compile(cfg, schema)
except ConfigError as exc:
    print("Error in ", args.ini_file, ": does not comply to schema:", exc.args[0])
    sys.exit(1)

fout = open(args.bin_file, "wb")
fout.write(binary)
