#!/usr/bin/python2

import sys
import argparse
from collections import OrderedDict

parser = argparse.ArgumentParser(
    description="Merge key-value environments, output to stdout")
parser.add_argument('input', nargs='+',
    help='Input files with environments to merge')
args = parser.parse_args()

d = OrderedDict()
for f in args.input:
    fin = open(f, "r")
    line_num = 0
    for line in fin:
        line = line.strip()
        if len(line) == 0 or line.startswith('#'):
            continue
        # k, v = line.split('=', maxsplit=1) # PY3
        tok = line.split('=')
        k = tok[0]
        if len(tok) < 2:
            raise Exception("syntax error on line: %u" % line_num)
        v = "=".join(tok[1:])
        d[k] = v
        line_num += 1
    fin.close()

for k in d:
    sys.stdout.write(k + '=' + d[k] + "\n")
