#!/usr/bin/python2

import sys
import argparse
from collections import OrderedDict

parser = argparse.ArgumentParser(
    description="Merge memory maps, output to stdout")
parser.add_argument('input', nargs='+',
    help='Input files with memory maps to merge')
args = parser.parse_args()

def write_fields(f, *fields):
    TAB_WIDTH = 8 # spaces
    FIELD_WIDTH = 4 # tabs
    for e in fields:
        tabs = FIELD_WIDTH - len(e) / TAB_WIDTH
        tabs = tabs if tabs >= 0 else 0
        padding = "\t" * tabs
        f.write(e + padding)
    f.write("\n")

d = OrderedDict()
for f in args.input:
    fin = open(f, "r")
    line_num = 0
    for line in fin:
        line = line.strip()
        if len(line) == 0 or line.startswith('#'):
            continue
        tok = line.split()
        if len(tok) < 3:
            raise Exception("syntax error on line: %u" % line_num)
        k = tok[0]
        addr = tok[1]
        fname = "\t".join(tok[2:])
        if k in d:
            if addr == '*':
                addr = d[k]["addr"]
            if fname == '*':
                fname = d[k]["fname"]
        d[k] = {"addr": addr, "fname": fname}
        line_num += 1
    fin.close()

for k in d:
    write_fields(sys.stdout, k, d[k]["addr"], d[k]["fname"])
