# Process raw Zebu memory dump into a memory image
# Also, extract the ramoops buffer.

BASE = 0x80000000
RAMOOPS_BASE = 0x83c00000
RAMOOPS_SIZE = 0x400000

%.bin: %.hex
	hpsc-objcopy -I Verilog-H -O binary $< $@

%.bin: %.dmp.bin
	dd if=$< of=$@ bs=24 skip=1

memory.bin: memory0.bin memory1.bin
	memstripe -b $(BASE) -o $@ $^

ramoops.bin: memory.bin
	dd if=$< of=$@ bs=4096 skip=$$((($(RAMOOPS_BASE) - $(BASE))/4096)) count=$$(($(RAMOOPS_SIZE)/4096))
